### PR TITLE
Bump all dependency package versions

### PR DESCRIPTION
**Pull request by zazaian**
This PR bumps all package dependencies to use most current major and minor versions of each library. In particular `poison` was dependent on hackney 1.6.6, which was deprecated and threw errors when building dependencies for an app in which recaptcha is being used.

exdoc was left at `>= 0.0.0` for compatibility purposes.

I've run the tests for recaptcha after each dependency bump and there were no failures. This should be ready to merge into master.

### CODE REVIEW

**Comment by sobolevn** [comment]
Maybe a package version bump too?

**Comment by zazaian** [comment]
Hey @sobolevn - I've issued a [2.1.2 release](https://github.com/zazaian/recaptcha/releases/tag/2.1.2) on [my fork](https://github.com/zazaian/recaptcha) for the time being so I can develop around these updates until there are updates with the PR. Feel free to use that for now as it's not going anywhere. I've just integrated it into my mix project for the time being with:

```
  defp deps do
    # deliberately exluding other system deps
    [{:recaptcha, github: "zazaian/recaptcha", tag: "2.1.2"}]
  end
```

**Comment by samueljseay** [comment]
Happy to merge this as is. We can bump `recaptcha` in a separate PR. I'll try get to that today. Thanks @zazaian 😄

**Comment by zazaian** [comment]
Sounds good, thanks a bunch @samueljseay and @sobolevn! I've got some additional contributions that I'll mention in a separate issue.

**Pull request merged**
