### PR TITLE
Update test/recaptcha_test.exs

### PR DESCRIPTION
**Pull request by odiumediae**
Replace duplicate Google test secret string with module attribute.

### CODE REVIEW

**Comment by sobolevn** [comment]
This is quite strange. @samueljseay can you have a look at the failing test?

**Comment by samueljseay** [comment]
@sobolevn thanks, yes I'll take a look at this

**Comment by samueljseay** [comment]
@sobolevn as far as I can tell it looks like the behaviour of Google's test key has changed. All requests for verification pass regardless of the key given. For now the simplest approach is to remove that test.

**Comment by samueljseay** [comment]
Thanks for your contribution @odiumediae  good spotting of that redundant string. I'm gonna close this in favour of #26

**Pull request closed without merging**
